name: 'entigo-k8s-gitops'
author: 'Entigo'
description: 'A GitHub Action that updates yamls files in git repos and synchronizes argocd'
inputs:
  command:
    description: 'Command to invoke update(git_repo,git_branch,git_key,images,app_path) or argocd-update(argocd_server,argocd_token,app_name,images)'
    required: true
    default: "update"
  git_repo:
    description: 'Git repo where yamls files are'
    required: false
  git_branch:
    description: 'Git repo branch where yamls files are'
    required: false
    default: "main"
  git_key:
    description: 'Git repo private key with write access'
    required: true
  images:
    description: 'Image tags to update to'
    required: true
  app_path:
    description: 'Path where yaml files are in the repo'
    required: false
    default: "."
  app_name:
    description: 'Argocd Application name to update.'
    required: false
    default: ""
  argocd_server:
    description: 'URL of argocd'
    required: false
  argocd_token:
    description: 'Authentication token for argocd'
    required: false
runs:
  using: 'docker'
  image: 'docker://entigolabs/entigo-k8s-gitops:main-latest'
  args:
    - /github-entrypoint.sh
